### PR TITLE
DEVOPS-3259: Update VERSION

### PR DESCRIPTION
**Pull request by HarshitaInfoblox**
https://infoblox.atlassian.net/browse/DEVOPS-3259

### CODE REVIEW

**Review by darrowmire — APPROVED** [review]

**Comment by tgjonestx** [comment]
We should incorporate this image into our Secure CICD process - please follow the instructions [here](https://docs.google.com/document/d/1u8dGR1EpwbHlUPcB-SJU66qSp0pz8Nr0BuSPIH6-CKM/edit#) to create a Jenkins job for this repo

**Review by tgjonestx — CHANGES_REQUESTED** [review]
We should incorporate this image into our Secure CICD process - please follow the instructions [here](https://docs.google.com/document/d/1u8dGR1EpwbHlUPcB-SJU66qSp0pz8Nr0BuSPIH6-CKM/edit#) to create a Jenkins job for this repo

**Comment by gshirazi** [comment]
this should be against `helm3` branch

**Comment by HarshitaInfoblox** [comment]
Closing this. Created #14 against helm3 branch.

**Pull request closed without merging**
